name: Apple Silicon Assembly CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-14 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Project
        run: make

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prime-benchmark-mac-arm64
          path: asm-prime-bench
          retention-days: 5
